feat;SomeInputValidation
mDemianchuk/walit pull request #23
Opened 2019-03-28 17:36 UTC by asbel

2019-03-28 20:41 UTC, mDemianchuk commented on assets/scripts/transactions.js
> +const moment = require('moment');
move to a separate file

2019-03-28 20:41 UTC, mDemianchuk commented on assets/scripts/transactions.js
> +//function numbersOnly()
remove the comments

2019-03-28 20:42 UTC, mDemianchuk commented on assets/scripts/transactions.js
> +    dateColumn = moment(dateColumn);
create a new method in 'date-util.js'

2019-03-28 20:43 UTC, mDemianchuk commented on assets/scripts/transactions.js
> +    let amount = setInputFilter(document.getElementById("amount"), function(value) {
create a new util file for that

2019-03-28 20:43 UTC, mDemianchuk commented on package.json
> +  "dependencies": {
move to devDependencies

2019-03-28 20:44 UTC, mDemianchuk commented on assets/html/bills.html
> +<script src="./../../dist/transactions.js"></script>
should be a separate file for input validation

2019-03-28 20:45 UTC, mDemianchuk commented on assets/scripts/index.js
> +const express = require('express')
delete this file

2019-03-28 20:45 UTC, mDemianchuk commented on settings.gradle
> +include ':app'
delete this file

2019-03-28 20:49 UTC, mDemianchuk commented on assets/scripts/transactions.js
> +  ["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function(event) {
should be single quotes

2019-03-28 20:49 UTC, mDemianchuk commented on assets/scripts/transactions.js
> +      } else if (this.hasOwnProperty("oldValue")) {
single quotes here

2019-03-28 21:02 UTC, nickdemianchuk requested changes
please address all of the comments

2019-04-03 19:38 UTC, asbel commented on assets/scripts/transactions.js
> +const moment = require('moment');
I did to one in the util folder

2019-04-19 21:03 UTC, closed without merging